model:
  save_name: "checkpoint.pth.tar"
  load_name: "checkpoint.pth.tar"
  load_model: TRUE
  eval_mode: TRUE


training:
  batch size: 24
  num_workers: 5
  num_epochs: 100
  learning_rate: 1e-4

images:
  img_h: 340
  img_w: 300
  pad_h: 3000
  pad_w: 3400
