model:
  save_name: ""
  load_name: "model_mid_750_850_4_5_100_1e-4_1.pth.tar"
  load_model: TRUE
  eval_mode: TRUE


training:
  batch_size: 1
  num_workers: 5
  num_epochs: 1
  learning_rate: 1e-4

images:
  img_h: 750
  img_w: 850
  pad_h: 3000
  pad_w: 3400
